language: java
services:
- docker

before_install:
- docker build -t jpreuss00/crawler .
- docker run -d -p 127.0.0.1:80:4567 jpreuss00/crawler /bin/sh -c "cd /root/crawler;
  bundle exec foreman start;"
- docker ps -a
- docker run jpreuss00/crawler /bin/sh -c "cd /root; bundle exec rake test"
script:
- bundle exec rake test

script:
  - travis env set DOCKER_USERNAME myusername
  - travis env set DOCKER_PASSWORD secretsecret
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jpreuss00/crawler:latest