language: java
services:
- docker



script:
  - travis login --org --github-token "$GITHUB_TOKEN"
  - travis env set DOCKER_USERNAME myusername
  - travis env set DOCKER_PASSWORD secretsecret
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jpreuss00/crawler:latest