language: java
services:
- docker

before_install:
- gradle test
- gem install travis
script:
- docker build -t jpreuss00/crawler .

script:
  - travis env set DOCKER_USERNAME myusername
  - travis env set DOCKER_PASSWORD secretsecret
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jpreuss00/crawler:latest