language: java
services:
- docker

before_install:
- gem install travis
- travis login
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- travis env set Username myusername
- travis env set Password secretsecret

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jpreuss00/crawler:latest