language: java
services:
- docker

before_install:
- gem install travis
- travis login --org --github-token ${GITHUB_TOKEN} --pro
- travis env set DOCKER_USERNAME myusername
- travis env set DOCKER_PASSWORD secretsecret
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker push jpreuss00/crawler:latest